#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7

bspc config pointer_modifier      mod1
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config border_width          0
bspc config window_gap            10
bspc config config split_ratio    0.50
bspc config presel_feedback_color "#BEF8C1"

pgrep polybar | xargs kill
pgrep bspc | xargs kill
polybar -c ~/.config/polybar/config.ini main &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom &
flameshot &
~/Scripts/chwall.sh &
~/Scripts/on_desktop_change.sh &
